export const checkFullName = 'Mr. fNAutomation3 lNAutomation3'
export const checkCompany = 'Believe'
export const checkAddress = 'Av.Blanco Galindo km 3/2'
export const checkCity = 'Texas Houston 0000'
export const checkCountry = 'United States'
export const checkPhone = '59172708582'
export const checkProductName24 = '[href="/product_details/24"]'
export const placeOrderButton = '[href="/payment"]'
export const paymentUrl = '/payment'
export const checkProductName29 = '[href="/product_details/29"]'