export const kidsCategoryOption = '[href="#Kids"]'
export const topsShirtOption = '[href="/category_products/5"]'
export const kidsCategoryHeader = 'Kids - Tops & Shirts Products'
export const brandOption = '[href="/brand_products/Polo"]'
export const brandHeader = 'Brand - Polo Products'