export const hoverProduct = '.product-image-wrapper'
export const addProductButton = '[data-product-id="24"]'
export const addMessageText = 'Your product has been added to cart.'
export const viewCartButton = '[href="/view_cart"]'
export const viewCartUrl = '/view_cart'
export const shoppingCart = '.active'
export const tittleItem = '[href="/product_details/24"]'
export const checkoutButton = '[class="btn btn-default check_out"]'
export const checkoutUrl = '/checkout'

// Group 2 - Purchase from brand and send review
export const productBrand29 = '[href="/product_details/29"]'
export const nameProductBrand29 = 'Green Side Placket Detail T-Shirt'
export const priceProductBrand29 = 'Rs. 1000'
export const reviewNameInput = '#name'
export const reviewEmailInput = '#email'
export const reviewTextInput = '[name="review"]'
export const reviewSubmitButton = '#button-review'
export const reviewSuccessMessage = 'Thank you for your review.'
export const addToCartButtonProduct29 = '.cart'
export const viewCartLinkProduct29 = '[href="/view_cart"]'