export const hoverProduct = '.product-image-wrapper'
export const addProductButton = '[data-product-id="24"]'
export const addMessageText = 'Your product has been added to cart.'
export const viewCartButton = '[href="/view_cart"]'
export const viewCartUrl = '/view_cart'
export const shoppingCart = '.active'
export const tittleItem = '[href="/product_details/24"]'
export const checkoutButton = '[class="btn btn-default check_out"]'
export const checkoutUrl = '/checkout'